version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - localstack

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # Remova ou comente o sysctls
    # sysctls:
    #   - vm.max_map_count=1677720
    #   - vm.swappiness=1
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

volumes:
  mongo-data: